# Generated by Django 5.0.6 on 2024-07-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_profile_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
    ]
